apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-l7nt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-l7nt
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-l7nt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-l7nt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-l7nt
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/happy-path-tenant/appstudio/dc-metro-map-l7nt@sha256:a8581f57dd41c854da165f608e6263b0599d54fc973206de7af3f71bf8ecfacb
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
